### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [kieraw/tc359-project10#1]
This is looking very good overall. I just have a few tweaks I'd like you to make:

A specific message on the `:name` and `:supplier` format validations would be helpful I think, so that the user can see what characters *are* allowed, rather than just being told that what they entered was invalid.

The Ruby `and` operator doesn't act quite the same way as `&&`, which is what you'd really want [in this case](https://github.com/kieraw/tc359-project10/blob/master/app/models/store.rb#L9). [This video](http://devblog.avdi.org/2014/08/26/how-to-use-rubys-english-andor-operators-without-going-nuts/) does a really good job at explaining the difference between the two.

Since you only want users to specify dates that are not in the past, an additional tweak that would be helpful would be to [specify the `:start_year` on the `date_select`](http://apidock.com/rails/ActionView/Helpers/DateHelper/date_select) so that the first year shown is the current year.

Let me know when these are done and I'll take another look.

**Comment by kieraw** [comment]
@chrisvfritz Done.

**Comment by chrisvfritz** [comment]
Fantastic! *One more* tiny thing. Instead of hardcoding 2015 into the date select, is there a way we could  always start with the current year, no matter what it is?

**Comment by kieraw** [comment]
@chrisvfritz Done.

**Comment by chrisvfritz** [comment]
:+1: Magnifique!
